"""Factor crowding detection engine.

Based on "Crowded Spaces and Anomalies" (Journal of Banking & Finance, Oct 2025):
- Anomaly returns are primarily generated by the most/least crowded stocks
- Crowding itself predicts which anomalies will work
- Results remain significant after publication dates

Crowding signals:
1. Factor return correlation clustering (when many assets load on same factor)
2. Factor HHI concentration (from existing heat score)
3. Return co-movement spikes (correlation regime changes)
4. Volume/flow concentration into factor ETFs
5. Short interest concentration
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class CrowdingSignal:
    """A single crowding signal measurement."""
    name: str
    value: float  # 0-1 normalized
    raw_value: float
    percentile: float = 0.5  # vs history
    description: str = ""


@dataclass
class CrowdingState:
    """Overall crowding assessment."""
    composite_score: float = 0.0  # 0=uncrowded, 1=extremely crowded
    level: str = "normal"  # normal, elevated, crowded, extreme
    signals: list[CrowdingSignal] = field(default_factory=list)
    most_crowded_factor: str = ""
    crowding_alpha_signal: float = 0.0  # Negative = expect mean reversion
    timestamp: str = ""


class CrowdingEngine:
    """Detect factor crowding as an alpha signal and risk indicator.

    Crowding = too many market participants concentrated in the same
    factor exposure. When crowding unwinds, correlated losses ensue.
    """

    def __init__(
        self,
        lookback: int = 60,
        history_max: int = 504,
        crowding_threshold_elevated: float = 0.5,
        crowding_threshold_crowded: float = 0.7,
        crowding_threshold_extreme: float = 0.85,
    ):
        self.lookback = lookback
        self.history_max = history_max
        self.threshold_elevated = crowding_threshold_elevated
        self.threshold_crowded = crowding_threshold_crowded
        self.threshold_extreme = crowding_threshold_extreme

        # History for percentile computation
        self._composite_history: list[float] = []
        self._signal_history: dict[str, list[float]] = {}

    def compute_crowding(
        self,
        position_returns: pd.DataFrame,
        factor_returns: pd.DataFrame,
        factor_exposures: dict[str, float],  # factor_name -> total_exposure
        correlation_matrix: pd.DataFrame | None = None,
        avg_correlation: float = 0.0,
    ) -> CrowdingState:
        """Compute comprehensive crowding assessment.

        Args:
            position_returns: Position return series.
            factor_returns: Factor ETF return series.
            factor_exposures: Current factor exposure dict.
            correlation_matrix: Current correlation matrix.
            avg_correlation: Current average pairwise correlation.
        """
        signals = []

        # Signal 1: Factor exposure concentration (HHI)
        hhi_signal = self._factor_concentration_signal(factor_exposures)
        signals.append(hhi_signal)

        # Signal 2: Cross-sectional return dispersion
        dispersion_signal = self._return_dispersion_signal(position_returns)
        signals.append(dispersion_signal)

        # Signal 3: Factor return co-movement
        comovement_signal = self._factor_comovement_signal(factor_returns)
        signals.append(comovement_signal)

        # Signal 4: Average correlation level
        corr_signal = self._correlation_level_signal(avg_correlation)
        signals.append(corr_signal)

        # Signal 5: Factor beta dispersion (are betas converging?)
        beta_signal = self._beta_convergence_signal(
            position_returns, factor_returns
        )
        signals.append(beta_signal)

        # Composite score (weighted average)
        weights = {
            "factor_concentration": 0.25,
            "return_dispersion": 0.15,
            "factor_comovement": 0.25,
            "correlation_level": 0.20,
            "beta_convergence": 0.15,
        }
        composite = sum(
            s.value * weights.get(s.name, 0.2)
            for s in signals
        )
        composite = float(np.clip(composite, 0, 1))

        # Update history
        self._composite_history.append(composite)
        if len(self._composite_history) > self.history_max:
            self._composite_history = self._composite_history[-self.history_max:]

        # Percentile vs history
        if len(self._composite_history) > 10:
            percentile = float(np.mean(
                np.array(self._composite_history[:-1]) <= composite
            ))
        else:
            percentile = 0.5

        # Classify level
        if composite >= self.threshold_extreme:
            level = "extreme"
        elif composite >= self.threshold_crowded:
            level = "crowded"
        elif composite >= self.threshold_elevated:
            level = "elevated"
        else:
            level = "normal"

        # Most crowded factor
        most_crowded = ""
        if factor_exposures:
            abs_exp = {k: abs(v) for k, v in factor_exposures.items()}
            most_crowded = max(abs_exp, key=abs_exp.get) if abs_exp else ""

        # Alpha signal: when crowding is extreme, expect mean reversion
        # Negative alpha signal = bet against the crowd
        alpha_signal = self._compute_alpha_signal(composite, percentile)

        return CrowdingState(
            composite_score=composite,
            level=level,
            signals=signals,
            most_crowded_factor=most_crowded,
            crowding_alpha_signal=alpha_signal,
            timestamp=datetime.utcnow().isoformat(),
        )

    def _factor_concentration_signal(
        self, factor_exposures: dict[str, float]
    ) -> CrowdingSignal:
        """HHI of factor exposures — concentrated = crowded."""
        if not factor_exposures:
            return CrowdingSignal(
                name="factor_concentration", value=0.0, raw_value=0.0,
                description="No factor data"
            )

        abs_exposures = np.array([abs(v) for v in factor_exposures.values()])
        total = abs_exposures.sum()
        if total == 0:
            return CrowdingSignal(
                name="factor_concentration", value=0.0, raw_value=0.0,
                description="Zero total exposure"
            )

        shares = abs_exposures / total
        hhi = float(np.sum(shares ** 2))

        # Normalize: HHI ranges from 1/N to 1
        n = len(abs_exposures)
        min_hhi = 1.0 / n if n > 0 else 0
        normalized = (hhi - min_hhi) / (1.0 - min_hhi) if (1.0 - min_hhi) > 0 else 0

        return CrowdingSignal(
            name="factor_concentration",
            value=float(np.clip(normalized, 0, 1)),
            raw_value=hhi,
            description=f"HHI={hhi:.3f} across {n} factors",
        )

    def _return_dispersion_signal(
        self, position_returns: pd.DataFrame
    ) -> CrowdingSignal:
        """Cross-sectional return dispersion — LOW dispersion = crowded.

        When stocks all move together, it means they're driven by the same factor.
        """
        if position_returns.empty or position_returns.shape[1] < 2:
            return CrowdingSignal(
                name="return_dispersion", value=0.5, raw_value=0.0,
                description="Insufficient data"
            )

        # Use recent window
        recent = position_returns.tail(min(self.lookback, len(position_returns)))

        # Cross-sectional standard deviation of returns, averaged over time
        cs_std = recent.std(axis=1).mean()

        # Track history
        hist_key = "return_dispersion"
        if hist_key not in self._signal_history:
            self._signal_history[hist_key] = []
        self._signal_history[hist_key].append(float(cs_std))
        if len(self._signal_history[hist_key]) > self.history_max:
            self._signal_history[hist_key] = self._signal_history[hist_key][-self.history_max:]

        # Low dispersion = high crowding signal
        # Percentile: lower dispersion = higher crowding
        history = self._signal_history[hist_key]
        if len(history) > 5:
            percentile = float(np.mean(np.array(history[:-1]) >= cs_std))
        else:
            percentile = 0.5

        return CrowdingSignal(
            name="return_dispersion",
            value=float(np.clip(percentile, 0, 1)),  # Inverted: low dispersion = high signal
            raw_value=float(cs_std),
            percentile=percentile,
            description=f"Cross-sectional σ={cs_std:.4f} (p{percentile:.0%})",
        )

    def _factor_comovement_signal(
        self, factor_returns: pd.DataFrame
    ) -> CrowdingSignal:
        """Average correlation between factor ETFs — high = crowded.

        When factors themselves become correlated, diversification disappears.
        """
        if factor_returns.empty or factor_returns.shape[1] < 2:
            return CrowdingSignal(
                name="factor_comovement", value=0.0, raw_value=0.0,
                description="Insufficient factor data"
            )

        recent = factor_returns.tail(min(self.lookback, len(factor_returns)))
        corr = recent.corr()

        # Average off-diagonal correlation
        n = len(corr)
        if n < 2:
            return CrowdingSignal(
                name="factor_comovement", value=0.0, raw_value=0.0,
            )

        mask = ~np.eye(n, dtype=bool)
        avg_corr = float(np.mean(corr.values[mask]))

        # Normalize: correlation from -1 to 1, map to 0-1
        # Higher avg correlation = more crowded
        normalized = float(np.clip((avg_corr + 1) / 2, 0, 1))

        # Track history
        hist_key = "factor_comovement"
        if hist_key not in self._signal_history:
            self._signal_history[hist_key] = []
        self._signal_history[hist_key].append(normalized)
        if len(self._signal_history[hist_key]) > self.history_max:
            self._signal_history[hist_key] = self._signal_history[hist_key][-self.history_max:]

        return CrowdingSignal(
            name="factor_comovement",
            value=normalized,
            raw_value=float(avg_corr),
            description=f"Factor avg ρ={avg_corr:.3f}",
        )

    def _correlation_level_signal(self, avg_correlation: float) -> CrowdingSignal:
        """Portfolio average correlation level — direct crowding indicator."""
        # Normalize: -1 to 1 -> 0 to 1
        normalized = float(np.clip((avg_correlation + 1) / 2, 0, 1))

        return CrowdingSignal(
            name="correlation_level",
            value=normalized,
            raw_value=float(avg_correlation),
            description=f"Portfolio avg ρ={avg_correlation:.3f}",
        )

    def _beta_convergence_signal(
        self,
        position_returns: pd.DataFrame,
        factor_returns: pd.DataFrame,
    ) -> CrowdingSignal:
        """Beta convergence — when all positions have similar factor betas, it's crowded.

        Measures cross-sectional dispersion of market betas.
        Low dispersion = everyone on the same trade.
        """
        if position_returns.empty or factor_returns.empty:
            return CrowdingSignal(
                name="beta_convergence", value=0.5, raw_value=0.0,
                description="No data"
            )

        # Use market factor (SPY) if available
        market_col = None
        for col in factor_returns.columns:
            if col.upper() in ("SPY", "MARKET"):
                market_col = col
                break

        if market_col is None and len(factor_returns.columns) > 0:
            market_col = factor_returns.columns[0]

        if market_col is None:
            return CrowdingSignal(
                name="beta_convergence", value=0.5, raw_value=0.0,
            )

        # Compute rolling betas for each position vs market
        recent = min(self.lookback, len(position_returns))
        pos_recent = position_returns.tail(recent)
        mkt_recent = factor_returns[market_col].tail(recent)

        common = pos_recent.index.intersection(mkt_recent.index)
        pos_recent = pos_recent.loc[common]
        mkt_recent = mkt_recent.loc[common]

        if len(common) < 20:
            return CrowdingSignal(
                name="beta_convergence", value=0.5, raw_value=0.0,
                description="Insufficient overlapping data"
            )

        betas = []
        mkt_var = float(mkt_recent.var())
        if mkt_var == 0:
            return CrowdingSignal(
                name="beta_convergence", value=0.5, raw_value=0.0,
            )

        for col in pos_recent.columns:
            cov = float(pos_recent[col].cov(mkt_recent))
            beta = cov / mkt_var
            betas.append(beta)

        if len(betas) < 2:
            return CrowdingSignal(
                name="beta_convergence", value=0.5, raw_value=0.0,
            )

        beta_std = float(np.std(betas))

        # Track history
        hist_key = "beta_convergence"
        if hist_key not in self._signal_history:
            self._signal_history[hist_key] = []
        self._signal_history[hist_key].append(beta_std)
        if len(self._signal_history[hist_key]) > self.history_max:
            self._signal_history[hist_key] = self._signal_history[hist_key][-self.history_max:]

        # Low beta dispersion = high crowding
        history = self._signal_history[hist_key]
        if len(history) > 5:
            percentile = float(np.mean(np.array(history[:-1]) >= beta_std))
        else:
            percentile = 0.5

        return CrowdingSignal(
            name="beta_convergence",
            value=float(np.clip(percentile, 0, 1)),
            raw_value=beta_std,
            percentile=percentile,
            description=f"β dispersion={beta_std:.3f} (p{percentile:.0%})",
        )

    def _compute_alpha_signal(
        self,
        composite: float,
        percentile: float,
    ) -> float:
        """Compute the crowding alpha signal.

        When crowding is extreme (>90th percentile), expect mean reversion.
        Alpha signal is negative = bet against the crowd.
        When crowding is low, alpha signal is positive = momentum persists.
        """
        if percentile > 0.9:
            # Extreme crowding: strong contrarian signal
            alpha = -(percentile - 0.5) * 2  # -0.8 to -1.0
        elif percentile > 0.7:
            # Elevated crowding: mild contrarian
            alpha = -(percentile - 0.5)  # -0.2 to -0.4
        elif percentile < 0.3:
            # Low crowding: momentum friendly
            alpha = (0.5 - percentile) * 0.5  # +0.1 to +0.25
        else:
            # Normal: no strong signal
            alpha = 0.0

        return float(np.clip(alpha, -1, 1))

    def to_dict(self) -> dict:
        """Serialize for API response."""
        state = self.compute_crowding.__func__  # Just for type hint
        # This returns from the last computed state
        if not hasattr(self, "_last_state"):
            return {"composite_score": 0, "level": "unknown", "signals": []}

        s = self._last_state
        return {
            "composite_score": round(s.composite_score, 4),
            "level": s.level,
            "most_crowded_factor": s.most_crowded_factor,
            "crowding_alpha_signal": round(s.crowding_alpha_signal, 4),
            "signals": [
                {
                    "name": sig.name,
                    "value": round(sig.value, 4),
                    "raw_value": round(sig.raw_value, 6),
                    "percentile": round(sig.percentile, 4),
                    "description": sig.description,
                }
                for sig in s.signals
            ],
            "timestamp": s.timestamp,
        }

    def compute_and_store(self, **kwargs) -> CrowdingState:
        """Compute crowding and store state for API access."""
        state = self.compute_crowding(**kwargs)
        self._last_state = state
        return state
