"""Configuration management for Risk Radar."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml
from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = PROJECT_ROOT / "config" / "settings.yaml"


class FactorETF(BaseSettings):
    """Single factor ETF definition."""
    name: str
    symbol: str
    description: str = ""


class Settings(BaseSettings):
    """Application settings — loaded from YAML + env vars."""

    # API Keys
    polygon_api_key: str = Field(
        default="", validation_alias=AliasChoices("POLYGON_API_KEY", "RISKRADAR_POLYGON_API_KEY")
    )
    fred_api_key: str = Field(
        default="", validation_alias=AliasChoices("FRED_API_KEY", "RISKRADAR_FRED_API_KEY")
    )
    telegram_bot_token: str = Field(
        default="",
        validation_alias=AliasChoices("TELEGRAM_BOT_TOKEN", "RISKRADAR_TELEGRAM_BOT_TOKEN"),
    )
    telegram_chat_id: str = Field(
        default="", validation_alias=AliasChoices("TELEGRAM_CHAT_ID", "RISKRADAR_TELEGRAM_CHAT_ID")
    )
    telegram_thread_id: int | None = Field(
        default=None,
        validation_alias=AliasChoices("TELEGRAM_THREAD_ID", "RISKRADAR_TELEGRAM_THREAD_ID"),
    )

    # Data
    factor_etfs: list[dict[str, str]] = Field(default_factory=list)
    portfolio_positions: list[dict[str, Any]] = Field(default_factory=list)

    # Engine parameters
    rolling_window: int = 60
    ewma_span: int = 60
    ar_lookback: int = 252
    heat_update_interval_seconds: int = 60

    # Heat score weights
    heat_weight_absorption_ratio: float = 0.25
    heat_weight_turbulence: float = 0.20
    heat_weight_diversification: float = 0.20
    heat_weight_factor_hhi: float = 0.15
    heat_weight_avg_correlation: float = 0.20

    # Alert thresholds generated by scripts/run_backtest.py.
    heat_threshold_warm: float = 0.4636
    heat_threshold_hot: float = 0.6732
    heat_threshold_critical: float = 0.8029
    heat_threshold_emergency: float = 0.8781

    # Data pipeline
    data_source_priority: list[str] = Field(default_factory=lambda: ["polygon", "yfinance", "cache"])
    polygon_tier: str = "free"
    data_cache_ttl_seconds: int = 300

    # Alert cooldowns (minutes)
    alert_cooldown_daily_summary: int = 1440
    alert_cooldown_level_change: int = 30
    alert_cooldown_threshold_cross: int = 60
    alert_cooldown_regime_shift: int = 15
    alert_cooldown_emergency: int = 0

    # Storage
    duckdb_path: str = str(PROJECT_ROOT / "data" / "riskradar.duckdb")
    delivery_log_path: str = str(PROJECT_ROOT / "data" / "delivery_log.jsonl")
    redis_url: str = "redis://localhost:6379"

    # Server
    host: str = "127.0.0.1"
    port: int = 8000

    model_config = SettingsConfigDict(
        env_prefix="RISKRADAR_",
        env_file=".env",
        populate_by_name=True,
        extra="ignore",
    )

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        """Make environment variables override values loaded from YAML."""
        return env_settings, dotenv_settings, init_settings, file_secret_settings

    @classmethod
    def from_yaml(cls, path: Path | str = DEFAULT_CONFIG) -> "Settings":
        """Load settings from YAML file, with env var overrides."""
        path = Path(path)
        data: dict[str, Any] = {}
        if path.exists():
            with open(path) as f:
                data = yaml.safe_load(f) or {}
            logger.info("Loaded config from %s", path)
        else:
            logger.warning("Config file not found: %s — using defaults", path)
        forbidden = {
            "polygon_api_key",
            "fred_api_key",
            "telegram_bot_token",
            "telegram_chat_id",
            "telegram_thread_id",
        }
        present = sorted(forbidden.intersection(data))
        if present:
            raise ValueError(
                "Secret and Telegram routing settings must come from environment variables, "
                f"not YAML: {', '.join(present)}"
            )

        positions_path = path.parent / "positions.yaml"
        if positions_path.exists():
            with open(positions_path) as f:
                positions_data = yaml.safe_load(f) or {}
            data["portfolio_positions"] = positions_data.get("portfolio_positions", [])
            logger.info("Loaded positions from %s", positions_path)

        return cls(**data)


# Default factor ETFs
DEFAULT_FACTOR_ETFS = [
    {"name": "rates", "symbol": "TLT", "description": "Duration / rate sensitivity"},
    {"name": "credit", "symbol": "HYG", "description": "HY spread / deleveraging"},
    {"name": "dollar", "symbol": "UUP", "description": "DXY / FX translation"},
    {"name": "ai_tech", "symbol": "SMH", "description": "Semiconductor / AI beta"},
    {"name": "quality", "symbol": "QUAL", "description": "Quality factor crowding"},
    {"name": "momentum", "symbol": "MTUM", "description": "Momentum crowding"},
    {"name": "market", "symbol": "SPY", "description": "Beta baseline"},
    {"name": "low_vol", "symbol": "USMV", "description": "Defensive positioning"},
    {"name": "value", "symbol": "VTV", "description": "Value factor"},
]

# Default FRED series
DEFAULT_FRED_SERIES = {
    "DGS10": "10Y Treasury Yield",
    "DGS2": "2Y Treasury Yield",
    "BAMLH0A0HYM2": "HY Credit Spread (OAS)",
    "SOFR": "SOFR Overnight Rate",
    "DTWEXBGS": "Broad Dollar Index",
    "VIXCLS": "VIX",
    "T10YIE": "10Y Breakeven Inflation",
}
